from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from typing import Literal
from uuid import uuid4

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from starlette.responses import StreamingResponse

app = FastAPI(
    title="PromptDeck API",
    version="0.1.0",
    description="Local development API for the PromptDeck prompt playground.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class Provider(BaseModel):
    id: str
    name: str
    model: str
    color: str
    configured: bool = False


class Message(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    role: Literal["user", "assistant", "system"]
    content: str
    model: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class Conversation(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    title: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    messages: list[Message] = Field(default_factory=list)


class ConversationCreate(BaseModel):
    title: str = Field(min_length=1, max_length=120)


class ChatRequest(BaseModel):
    provider: str = "openai"
    model: str = "gpt-4o"
    prompt: str = Field(min_length=1, max_length=50_000)
    system_prompt: str = "You are a helpful assistant."
    temperature: float = Field(default=0.7, ge=0, le=2)
    max_tokens: int = Field(default=1024, ge=1, le=16_384)
    conversation_id: str | None = None


PROVIDERS = [
    Provider(id="openai", name="OpenAI", model="gpt-4o", color="#10a37f"),
    Provider(id="anthropic", name="Anthropic", model="claude-3-5-sonnet", color="#d97757"),
    Provider(id="google", name="Google", model="gemini-1.5-pro", color="#4285f4"),
    Provider(id="groq", name="Groq", model="llama-3.3-70b", color="#f55036"),
    Provider(id="ollama", name="Ollama", model="llama3.2", color="#a8a29e", configured=True),
]

CONVERSATIONS: dict[str, Conversation] = {}


def now() -> datetime:
    return datetime.now(UTC)


def create_demo_reply(request: ChatRequest) -> str:
    subject = request.prompt.strip().replace("\n", " ")
    if len(subject) > 150:
        subject = f"{subject[:147]}..."
    provider = next((item for item in PROVIDERS if item.id == request.provider), None)
    provider_name = provider.name if provider else request.provider.title()
    return (
        f"Here is a practical plan for **{subject}**\n\n"
        "1. **Start with a resilient baseline.** Use a rolling deployment, explicit resource requests and limits, "
        "and readiness probes so only healthy pods receive traffic.\n"
        "2. **Protect availability.** Spread replicas across failure domains, set a PodDisruptionBudget, and configure "
        "horizontal autoscaling from meaningful signals such as CPU, queue depth, or request concurrency.\n"
        "3. **Make changes observable.** Emit structured logs, track error rate and latency, and attach deployment metadata "
        "to traces so a rollback decision is evidence-based.\n"
        "4. **Test the failure path.** Verify rollout rollback behavior, a lost node, a dependency timeout, and a bad configuration "
        "before relying on the runbook in production.\n\n"
        f"_Generated by PromptDeck's local {provider_name} mock gateway using {request.model} at temperature {request.temperature:.1f}. "
        "Connect a provider key to replace this deterministic development response._"
    )


def sse(event_type: str, payload: dict[str, object]) -> str:
    return f"event: {event_type}\ndata: {json.dumps(payload)}\n\n"


async def stream_response(request: ChatRequest, conversation: Conversation) -> AsyncIterator[str]:
    reply = create_demo_reply(request)
    for token in reply.split(" "):
        yield sse("message", {"type": "token", "content": f"{token} "})
        await asyncio.sleep(0.018)

    assistant_message = Message(role="assistant", content=reply, model=request.model)
    conversation.messages.append(assistant_message)
    conversation.updated_at = now()
    yield sse(
        "message",
        {
            "type": "complete",
            "conversation_id": conversation.id,
            "message_id": assistant_message.id,
            "usage": {"prompt_tokens": len(request.prompt.split()), "completion_tokens": len(reply.split())},
        },
    )


@app.get("/health", tags=["system"])
def health() -> dict[str, str]:
    return {"status": "ok", "service": "promptdeck-api"}


@app.get("/api/providers", response_model=list[Provider], tags=["providers"])
def list_providers() -> list[Provider]:
    return PROVIDERS


@app.get("/api/conversations", response_model=list[Conversation], tags=["conversations"])
def list_conversations() -> list[Conversation]:
    return sorted(CONVERSATIONS.values(), key=lambda conversation: conversation.updated_at, reverse=True)


@app.post("/api/conversations", response_model=Conversation, status_code=201, tags=["conversations"])
def create_conversation(payload: ConversationCreate) -> Conversation:
    conversation = Conversation(title=payload.title)
    CONVERSATIONS[conversation.id] = conversation
    return conversation


@app.get("/api/conversations/{conversation_id}", response_model=Conversation, tags=["conversations"])
def get_conversation(conversation_id: str) -> Conversation:
    conversation = CONVERSATIONS.get(conversation_id)
    if conversation is None:
        raise HTTPException(status_code=404, detail="Conversation not found")
    return conversation


@app.post("/api/chat/stream", tags=["chat"])
async def chat_stream(request: ChatRequest) -> StreamingResponse:
    conversation: Conversation
    if request.conversation_id:
        conversation = CONVERSATIONS.get(request.conversation_id)  # type: ignore[assignment]
        if conversation is None:
            raise HTTPException(status_code=404, detail="Conversation not found")
    else:
        title = request.prompt.strip().split("\n", maxsplit=1)[0][:72]
        conversation = Conversation(title=title or "Untitled playground")
        CONVERSATIONS[conversation.id] = conversation

    conversation.messages.append(Message(role="system", content=request.system_prompt))
    conversation.messages.append(Message(role="user", content=request.prompt))
    conversation.updated_at = now()
    return StreamingResponse(
        stream_response(request, conversation),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive", "X-Accel-Buffering": "no"},
    )
